version: "3.3"
services:
  cs2:
    image: cs2_server:0.2.6
    container_name: cs2-ds
    volumes:
      - type: bind
        source: ${HOME}/Downloads/cs2_app
        target: /data/steam/csgo_app
      - type: bind
        source: ${PWD}/csgo_scripts
        target: /data/steam/csgo_git_repo/csgo_scripts
    network_mode: host
    restart: unless-stopped
    command: /data/steam/csgo_git_repo/csgo_scripts/run_cs2_server.sh
  filebeat:
    image: elastic/filebeat:8.10.1
    container_name: filebeat
    volumes:
      - type: bind
        source: ${HOME}/Downloads/cs2_app/game/csgo
        target: /data/steam/csgo_logs
      - type: bind
        source: ${PWD}/ansible_playbook/files/filebeat.docker.yml
        target: /usr/share/filebeat/filebeat.yml
    restart: unless-stopped
    command: filebeat -e --strict.perms=false 
  logstash:
    image: logstash:8.10.1
    container_name: logstash
    volumes:
      - type: bind
        source: ${PWD}/ansible_playbook/files/logstash_csgo_console_log.conf
        target: /usr/share/logstash/pipeline/csgo.conf
    restart: unless-stopped
  elasticsearch:
    image: elasticsearch:8.10.1
    container_name: elasticsearch
    ports:
    - "127.0.0.1:9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    #restart: unless-stopped
  kibana:
    image: kibana:8.10.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    restart: unless-stopped



