---
- name: playbook to install the SteamCMD cli client and CSGO server
  hosts: localhost
  tasks:
  - name: use apt to update its cache
    become: yes
    apt:
       update_cache: yes
  - name: install setfacl
    become: yes
    apt:
      update_cache: true
      package: acl
  - name: Add multiverse
    become: yes
    ansible.builtin.apt_repository:
      repo: "{{item}}"
      state: present
      update_cache: true
    with_items:
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-backports main restricted universe multiverse'
    - 'deb http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-security multiverse'
  - name: add software-properties-common
    become: yes
    apt:
       package: software-properties-common
       update_cache: yes
  - name: Enable i386 architecture
    become: yes
    command: /usr/bin/dpkg --add-architecture i386
  - name: use apt to update its cache
    become: yes
    apt:
       update_cache: yes
  - name: accept steam license
    become: yes
    debconf:
      name: "steam"
      question: "steam/question"
      value: "I AGREE"
      vtype: "select"
  - name: install steamcmd
    become: yes
    apt:
      update_cache: true
      package: ['ca-certificates', 'lib32gcc-s1', 'lib32stdc++6', 'libcurl4-gnutls-dev:i386', 'locales', 'steamcmd']
  - name: install various tools
    become: yes
    apt:
      update_cache: true
      package: ['curl', 'htop', 'less', 'vim']
  - name: add steam users
    become: yes
    user:
      name: "steam"
      comment: "SteamCMD owner"
      home: "/data/steam"
      shell: "/usr/bin/bash"
  - name: Adding ansible user to group steam
    become: yes
    user: 
      name: ansible
      groups: steam
      append: yes
  - name: Create the csgo_app directory
    become: yes
    become_user: steam
    ansible.builtin.file:
      path: /data/steam/csgo_app
      state: directory
      mode: '0755'
  - name: install csgo server
    become: yes
    become_user: steam
    ansible.builtin.command:
      creates: /data/steam/csgo_app/srcds_linux
      argv:
        - /usr/games/steamcmd 
        - +force_install_dir /data/steam/csgo_app
        - +login anonymous
        - +app_update 740 validate
        - +quit
  - name: install git repo with the scripts for the csgo server
    become: yes
    become_user: steam
    git:
      repo: 'https://github.com/henkoch/csgo_server.git'
      dest: /data/steam/csgo_git_repo
      update: yes
      version: intro_terraform
  - name: Generate autoexec.cfg from Template
    become: yes
    become_user: steam
    template:
      src: files/autoexec.cfg.j2
      dest: /data/steam/csgo_app/csgo/cfg/autoexec.cfg
