version: "3.3"
services:
  logstash:
    image: logstash:8.10.1
    container_name: logstash
    volumes:
      - type: bind
        source: ${PWD}/ansible_playbook/files/logstash_csgo_console_log.conf
        target: /usr/share/logstash/pipeline/csgo.conf
    restart: unless-stopped
  elasticsearch:
    image: elasticsearch:8.10.1
    container_name: elasticsearch
    ports:
    - "127.0.0.1:9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    #restart: unless-stopped
  kibana:
    image: kibana:8.10.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    restart: unless-stopped



