version: "3.3"
services:
  logstash:
    image: logstash:8.12.2
    container_name: logstash
    ports:
    - "5044:5044"
    volumes:
      - type: bind
        source: ${PWD}/logstash_csgo_console_log.conf
        target: /usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    restart: unless-stopped
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    ports:
    - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    #restart: unless-stopped
  kibana:
    image: kibana:8.12.2
    container_name: kibana
    ports:
    - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - type: bind
        source: ${PWD}/prometheus.yaml
        target: /etc/prometheus/prometheus.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:10.3.3
    container_name: grafana
    ports:
      - "3000:3000"
